-- MySQL Script generated by MySQL Workbench
-- Tue Dec 26 19:56:30 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_student` (
  `student_id` INT NOT NULL,
  `student_cpf` VARCHAR(45) NULL,
  `student_name` VARCHAR(45) NULL,
  `student_last_name` VARCHAR(45) NULL,
  `student_email` VARCHAR(45) NULL,
  `student_password` VARCHAR(32) NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`plan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`plan` (
  `plan_id` INT NOT NULL,
  `plan_price` FLOAT NOT NULL,
  `plan_name` VARCHAR(45) NOT NULL,
  `plan_duration` INT NOT NULL,
  `plan_description` VARCHAR(100) NULL,
  PRIMARY KEY (`plan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `payment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `payment_datetime` DATETIME NOT NULL,
  `payment_value` FLOAT NOT NULL,
  `payment_discount` FLOAT NULL,
  `payment_description` VARCHAR(100) NULL,
  `user_student_student_id` INT NOT NULL,
  `plan_plan_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  UNIQUE INDEX `payment_id_UNIQUE` (`payment_id` ASC),
  INDEX `fk_payment_user_student_idx` (`user_student_student_id` ASC),
  INDEX `fk_payment_plan1_idx` (`plan_plan_id` ASC),
  CONSTRAINT `fk_payment_user_student`
    FOREIGN KEY (`user_student_student_id`)
    REFERENCES `mydb`.`user_student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_plan1`
    FOREIGN KEY (`plan_plan_id`)
    REFERENCES `mydb`.`plan` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`problem_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`problem_topic` ;

CREATE TABLE IF NOT EXISTS `mydb`.`problem_topic` (
  `topic_id` INT NOT NULL,
  `topic_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`topic_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`problem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`problem` ;

CREATE TABLE IF NOT EXISTS `mydb`.`problem` (
  `problem_id` INT NOT NULL,
  `problem_name` VARCHAR(45) NOT NULL,
  `problem_topic_topic_id` INT NOT NULL,
  `problem_type` INT NOT NULL,
  `problem_type_id` INT NOT NULL,
  PRIMARY KEY (`problem_id`),
  INDEX `fk_problem_problem_topic1_idx` (`problem_topic_topic_id` ASC),
  CONSTRAINT `fk_problem_problem_topic1`
    FOREIGN KEY (`problem_topic_topic_id`)
    REFERENCES `mydb`.`problem_topic` (`topic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dependency_set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dependency_set` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dependency_set` (
  `dependency_id` INT NOT NULL,
  `dependency_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dependency_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`map_problem_dependency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`map_problem_dependency` ;

CREATE TABLE IF NOT EXISTS `mydb`.`map_problem_dependency` (
  `map_description` VARCHAR(100) NULL,
  `dependency_set_dependency_id` INT NOT NULL,
  `problem_problem_id` INT NOT NULL,
  PRIMARY KEY (`dependency_set_dependency_id`, `problem_problem_id`),
  INDEX `fk_map_problem_dependency_problem1_idx` (`problem_problem_id` ASC),
  CONSTRAINT `fk_map_problem_dependency_dependency_set1`
    FOREIGN KEY (`dependency_set_dependency_id`)
    REFERENCES `mydb`.`dependency_set` (`dependency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_map_problem_dependency_problem1`
    FOREIGN KEY (`problem_problem_id`)
    REFERENCES `mydb`.`problem` (`problem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_manager` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_manager` (
  `manager_id` INT NOT NULL,
  `manager_email` VARCHAR(45) NOT NULL,
  `manager_password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`manager_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maintenance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`maintenance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`maintenance` (
  `maintenance_id` INT NOT NULL,
  `maintenance_description` VARCHAR(100) NULL,
  `user_manager_manager_id` INT NOT NULL,
  `maintenance_datetime` DATETIME NULL,
  PRIMARY KEY (`maintenance_id`),
  INDEX `fk_maintenance_user_manager1_idx` (`user_manager_manager_id` ASC),
  CONSTRAINT `fk_maintenance_user_manager1`
    FOREIGN KEY (`user_manager_manager_id`)
    REFERENCES `mydb`.`user_manager` (`manager_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_problem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student_problem` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student_problem` (
  `student_problem_state` INT NULL,
  `user_student_student_id` INT NOT NULL,
  `problem_problem_id` INT NOT NULL,
  PRIMARY KEY (`user_student_student_id`, `problem_problem_id`),
  INDEX `fk_student_problem_problem1_idx` (`problem_problem_id` ASC),
  CONSTRAINT `fk_student_problem_user_student1`
    FOREIGN KEY (`user_student_student_id`)
    REFERENCES `mydb`.`user_student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_problem_problem1`
    FOREIGN KEY (`problem_problem_id`)
    REFERENCES `mydb`.`problem` (`problem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
