-- MySQL Script generated by MySQL Workbench
-- Tue Dec 26 20:52:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`check`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`check` ;

CREATE TABLE IF NOT EXISTS `mydb`.`check` (
  `check_id` INT NOT NULL,
  `check_description` VARCHAR(200) NULL,
  PRIMARY KEY (`check_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `item_id` INT NOT NULL,
  `item_description` VARCHAR(100) NOT NULL,
  `check_check_id` INT NOT NULL,
  `item_answer_key` INT NULL,
  PRIMARY KEY (`item_id`, `item_description`),
  INDEX `fk_item_check_idx` (`check_check_id` ASC),
  CONSTRAINT `fk_item_check`
    FOREIGN KEY (`check_check_id`)
    REFERENCES `mydb`.`check` (`check_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
